language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - extra-android-m2repository
    - android-23

script: ./gradlew clean :app:testDebugUnitTest